### ISSUE TITLE
ssh-agent support for sshfs://

### ISSUE THREAD

**Issue by quite** [IgnorantGuru/udevil#16]
Is this possible? I guess what makes it not work currently, is the fact that everything
is run as root. So ~root/.ssh/ is used, and the env SSH_AGENT_PID and SSH_AUTH_SOCK
are not inherited etc etc.

**Comment by IgnorantGuru** [comment]
SpaceFM 1.0.0 supports mounting sshfs as a normal user.
https://github.com/IgnorantGuru/spacefm/issues/478
