### ISSUE TITLE
go-mtpfs support

### ISSUE THREAD

**Issue by nedimlisica** [IgnorantGuru/udevil#23]
Hi,

Could you please add support for mounting mtp devices through go-mtpfs.
https://github.com/hanwen/go-mtpfs

Other implemetations are painfully slow and unstable while go-mtpfs works perfectly with my android phone.
Currently I'm running script to automount with udev rule, but it would be nice to see phones and media players as devices in SpaceFM.

Thanks.

**Comment by IgnorantGuru** [comment]
SpaceFM 1.0.0 is due for release soon, and it handles mtpfs via fuse.
https://github.com/IgnorantGuru/spacefm/issues/478
