### ISSUE TITLE
Kernel polling documention suggestions

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/udevil#40]
The need for reboot is slightly exaggerated.
Udev rules can be reloaded with:
```udevadm control --reload```
Therefore newly plugged in device will be set with correct polling interval.
Also one can trigger existing removable devices to be processed with new rule:
```udevadm trigger --attr-match=removable=1 --action=add --verbose```

**Comment by IgnorantGuru** [comment]
Was just to keep the instructions simple - those more familiar with Linux can reload components.  The docs aren't a udev manual, just giving tips.  Thanks for the info.
