### ISSUE TITLE
devmon doesn't display message if unmount failed

### ISSUE THREAD

**Issue by jdietrch** [IgnorantGuru/udevil#42]
I have udevil 0.4.3

When I run devmon --unmount-removable a box pops up saying

Unmounting /dev/sdc...

(This dialog will close when the devices are unmounted.)

Then the dialog goes away, but the device is not unmounted, because the device is busy. That's fine, but http://igurublog.wordpress.com/downloads/script-devmon/ says that "If an unmounting error occurs, a pop-up dialog will announce it." This dialog reporting the error is what I'm not seeing. Is there something else I need to do to get that error dialog to appear?

Thank you,
James Dietrich

**Comment by IgnorantGuru** [comment]
Thanks and sorry for the delay (development was suspended).  This has been fixed in devmon 1.1.8 due for release with udevil.  This is currently in the next branch for testing - see BUILD NEXT instructions in README.
