### ISSUE TITLE
Where (exactly) does it mount?

### ISSUE THREAD

**Issue by tz1** [IgnorantGuru/udevil#44]
I've tried looking for a manpage, the conf, and the rest, but I can't find something that explains exactly where a device will end up mounted.

Say I use udevil to mount /dev/sr0, then to mount /dev/sdb1 (removable USB).  Are both going to be mounted to /media?  Do I have to pre-create /media/something for each?  Will it create them?  If so, what will it create?  UUIDs?  Volume Labels?  /media/dev-sr0 /media/dev-sdb1?  What if I have two optical drives?  Do I have to have them all in /etc/fstab (which ordinary users normally don't have access rights to?

From the "usage" which is just the help dump:
    EXAMPLES:
    udevil mount /dev/sdd1
    udevil mount -o ro,noatime /dev/sdd1

OK, so it mounts /dev/sdd1.  Where?  The default config says somewhere under /media, but where under /media?  I can specify where, but not if I want automounting.  Nor does it say that it will or will not create /media/sdd1 if it doesn't exist if I do so.

The application is for a CLI only raspberry pi - I'm hoping to do a raspian deb package and use udevil, but I'm unlikely to use SpaceFM - which might handle it all in a way I can ignore everything when using it, but if it creates /run/media/whomeverIam/really-long-uuid123412o95u83958293409293478203unrelatedtothedevice and I have to decode it, it will be less useful.

What I really want to do is to have a /mnt directory, and for every /dev/sr* and /dev/sd[a-z][1-8], mount (maybe automatically) on /mnt/sd[a-z][1-8], 1 to 1.  And something similar and simple for network links.  I don't think that is what will happen by default, nor do I see a way in the conf file to achieve this.  Extra but unnecessary would be to add symlinks to/from UUIDs and/or Volume Labels.

I can run it and find out what it appears to do, and see if I can get it to do what I want, but this should be something documented somewhere easy to find and understand the exact behavior.  And on the manpage (is it really that stub or did I miss something)

**Comment by mihaiolteanu** [comment]
> If you don't specify a mount point (and there is none in fstab), then udevil will create one. Its name will be based on the volume label, or otherwise on the bus type, device id, etc.

How to mount **/dev/sda1**, on **/media/sda1**, for example?
That is, ignore the device label and use the device partition when (auto)mounting.

**Comment by jaimet** [comment]
> How to mount **/dev/sda1**, on **/media/sda1**, for example? That is, ignore the device label and use the device partition when (auto)mounting.

Just specify your desired mount point as the next parameter:

```
$ udevil mount /dev/sda1 /media/sda1
Mounted /dev/sda1 at /media/sda1
```

It would be great if this happened _by default_, but that is the intention of [this issue](https://github.com/IgnorantGuru/udevil/issues/84) and this [PR](https://github.com/IgnorantGuru/udevil/pull/86).

See [here](http://ignorantguru.github.io/udevil/udevil--help.html) for more usage examples. HTH.
