### ISSUE TITLE
Configuration tweaking required to mount an exfat volume

### ISSUE THREAD

**Issue by OmegaPhil** [IgnorantGuru/udevil#52]
By default attempting to mount an exfat volume through SpaceFM results in the following error:

```
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
FUSE exfat 1.0.1
```

I haven't looked at the code but a quick investigation suggests udevil creates the '/media/<volume name>/.udevil-mount-point' file inside the directory to mount over. As this is harmless, in order to get the volume to mount I:

1. Added a 'default_options_exfat' line to udevil.conf copying default_options and adding 'nonempty'.
2. Added 'nonempty' to the end of the allowed_options line.

After saving, the next mount attempt worked.

**Comment by IgnorantGuru** [comment]
Thanks, imported changes as described.  Testing appreciated.

**Comment by IgnorantGuru** [comment]
94ab62b add the following new default/allowed options:
~~~~
default_options_exfat     = nosuid, noexec, nodev, noatime, umask=0077, uid=$UID, gid=$GID, iocharset=utf8, namecase=0, nonempty
allowed_options_exfat     = nosuid, noexec, nodev, noatime, fmask=0133, dmask=0022, uid=$UID, gid=$GID, umask=0077, namecase=*, ro, rw, sync, flush, iocharset=*, remount, nonempty
~~~~
See [udisks2 commit](http://cgit.freedesktop.org/udisks/commit/?id=4d4b05974) and [debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=720695).

Please test in next - thanks.

**Comment by OmegaPhil** [comment]
Since this was just a config change, I have replicated locally - I have succeeded in creating an exfat volume, mounting, dumping a file on it, removing and remounting and hashing successfully - no complaints from SpaceFM.

**Comment by IgnorantGuru** [comment]
Thanks for testing.

**Comment by jalsti** [comment]
Just a note: with here udevil version 0.4.4 exactly that default option in udevil.conf did block mounting my exfat volume and I had to remove it. (Would maybe be cool to have a udevil command line option to prevent/override usage of some default options.)
