### ISSUE TITLE
[devmon] "exec-on-unmount" doesn't pass correct values

### ISSUE THREAD

**Issue by j1elo** [IgnorantGuru/udevil#56]
The command executed on unmount will replace `%d` and `%l` -the mount point and the label- using values from the latest mounted device, instead of the one being unmounted. The `%f` -device path-, however, is correct.

**Steps to reproduce**

1. Launch devmon with "--exec-on-unmount" option:
`./devmon --exec-on-unmount "echo [%d] [%f] [%l]"`

2. Insert first USB. Device is `/dev/sdb1`, label is `USB-A`, mount point is `/media/USB-A`.

3. Insert second USB. Device is `/dev/sdc1`, label is `USB-B`, mount point is `/media/USB-B`.

4. Unmount first USB:
`./devmon --unmount /media/USB-A`

**Obtained result**

The following is printed:
[/media/USB-B] [/dev/sdb1] [USB-B]

**Expected result**

The following should be printed:
[/media/USB-A] [/dev/sdb1] [USB-A]

or even, maybe:
[] [/dev/sdb1] [USB-A]
given the fact that the mount point, at this moment, doesn't actually exist any more (however it might come handy for scripts running after devices are unmounted).

**Comment by j1elo** [comment]
The mount point could be printed, even after unmount operation, if it was stored at mount time

**Comment by IgnorantGuru** [comment]
Thanks, this has been corrected in https://github.com/IgnorantGuru/udevil/commit/59fecbc965175b40b7f37404c916055942ecf9aa which unsets %l and %d.  (devmon does not cache mount points).

jfyi, that commit also makes --exec-on-unmount commands run for devices mounted during devmon startup (but still not for devices mounted prior to startup).  Not sure why I didn't do this originally so testing is appreciated, but it looks okay.

These changes are in devmon 1.1.8 distributed with the next udevil release.  For testing please see BUILD NEXT instructions in README.
