### ISSUE TITLE
How to mount under a home directory folder?

### ISSUE THREAD

**Issue by Aadniz** [IgnorantGuru/udevil#87]
Hi.

I'm trying to mount my file-share to `/home/username/Share` but it's giving me this error:

    udevil: denied 71: '/home/username' is not an allowed media directory

I couldn't find much information/documentation on this online, and wanted to ask here.

Is it possible to mount a files-hare under a folder in home directory? or would I need to symlink it?

**Comment by foursixnine** [comment]
You need to modify the 
`allowed_media_dirs = /media, /media/$USER, /run/media/$USER` to include `/home/$USER/Share` in /etc/udevil.conf (https://ignorantguru.github.io/udevil/udevil.conf.txt) and maybe, add udevil-user-$user.conf if you want only those changes to apply to your user....

**Comment by Aadniz** [comment]
Thanks a lot, I didn't even know there was a config file for udevil
